version: '2'
services:
  web:
    build: web
    ports:
      - "3000:3000"
    volumes_from:
      - web-data
    volumes:
      - ./web:/app
    environment:
      - PGHOST=postgres
    command: "make start"

  web-data:
    restart: always
    build: web
    volumes:
      - /data
    command: "true"

  postgres-data:
    restart: always
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    command: "true"

  postgres:
    restart: always
    image: postgres:latest
    volumes_from:
      - postgres-data
    ports:
      - "5432:5432"
