version: '2'
services:
  web:
    depends_on:
      - database
    build: web
    ports:
      - "3000:3000"
    volumes_from:
      - web-data
    volumes:
      - ./web:/app
    environment:
      - PGHOST=database
    command: "make start"

  web-data:
    restart: always
    build: web
    volumes:
      - /data
    command: "true"

  database-data:
    restart: always
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    command: "true"

  database:
    restart: always
    image: postgres:latest
    volumes_from:
      - database-data
    ports:
      - "5432:5432"
